#!/bin/bash

exec >"$(basename $0)".log 2>&1

cat > scratch/mykeyboard << EOF
keymap=fr-latin9
EOF
cat > scratch/myconf << EOF
# A comment

[settings]
keymapfile = $(pwd)/scratch/mykeyboard
EOF
. ${srcdir}/ref-dbus.sh
. ${srcdir}/ref-localed.sh --config scratch/myconf
gdbus introspect \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --only-properties | grep VConsoleKeymap | cmp ${srcdir}/scratch/keyboard-read-result1
RES=$?
rm scratch/mykeyboard scratch/myconf
. ${srcdir}/unref-localed.sh
. ${srcdir}/unref-dbus.sh
exit $RES
