#!/bin/bash

cat > scratch/locale << EOF
export LANG=fr_FR.UTF-8
export LC_COLLATE=\
\
C
EOF
. ${srcdir}/ref-dbus.sh
gdbus introspect \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --only-properties | grep Locale | cmp ${srcdir}/scratch/locale-read-result1
RES=$?
rm scratch/locale
. ${srcdir}/unref-dbus.sh
exit $RES
