#!/bin/bash

exec >"$(basename $0)".log 2>&1

cat > scratch/mylocale << EOF
export LANG=fr_FR.UTF-8
export LC_COLLATE=\\
\\
"fr_FR"
EOF
cat > scratch/myconf << EOF
# Config for localefile

[settings]
localefile=$(pwd)/scratch/mylocale
# keymapfile = /somedir/console

EOF
. ${srcdir}/ref-dbus.sh
. ${srcdir}/ref-localed.sh --config scratch/myconf
gdbus introspect \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --only-properties | grep Locale | cmp ${srcdir}/scratch/locale-read-result1
RES=$?
rm scratch/mylocale scratch/myconf
. ${srcdir}/unref-localed.sh
. ${srcdir}/unref-dbus.sh
exit $RES
