#!/bin/bash

exec >"$(basename $0)".log 2>&1

echo -en "LANG=\"en_US.UTF-8\"\nLC_TIME=\"en_GB.UTF-8\"" > scratch/locale
. ${srcdir}/ref-dbus.sh
. ${srcdir}/ref-polkit.sh
gdbus call \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --method org.freedesktop.locale1.SetLocale \
      "['LANG=fr_FR.UTF-8', 'LC_TIME=fr_FR.UTF-8', 'LC_COLLATE=fr_FR.UTF-8']" \
      true
cmp scratch/locale << EOF
LANG='fr_FR.UTF-8'
LC_TIME='fr_FR.UTF-8'
LC_COLLATE='fr_FR.UTF-8'
EOF

RES=$?
if [ $RES = 0 ]; then rm scratch/locale; fi
. ${srcdir}/unref-polkit.sh
. ${srcdir}/unref-dbus.sh
exit $RES
