#!/bin/bash

exec >"$(basename $0)".log 2>&1

cat > scratch/locale << EOF
        LANG=fr_FR.UTF-8
	LC_COLLATE=\\
\\
'fr'_"FR"
EOF
. ${srcdir}/ref-dbus.sh
gdbus introspect \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --only-properties | grep Locale | cmp ${srcdir}/scratch/locale-read-result1
RES=$?
rm scratch/locale
. ${srcdir}/unref-dbus.sh
exit $RES
