#!/bin/bash

exec >"$(basename $0)".log 2>&1

cat > scratch/xkeyboard << EOF
Section "InputClass"
        Identifier "libinput keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "XkbLayout" "fr"
        Option "Xkbvariant" "latin9"
        Option "xkbModel" "pc105"
        Option "xkboptions" "terminate:ctrl_alt_bksp"
EndSection
EOF
. ${srcdir}/ref-dbus.sh
gdbus introspect \
      --system \
      --dest org.freedesktop.locale1 \
      --object-path /org/freedesktop/locale1 \
      --only-properties | grep X11 | cmp ${srcdir}/scratch/xkeyboard-read-result1
RES=$?

if [ $RES = 0 ]; then
    echo PASS read-xkeyboard
    sleep 0.1
    cat > scratch/xkeyboard <<- EOF
	Section "InputClass"
	        Option "XkbLayout" "fr"
	EOF
    . ${srcdir}/ref-localed.sh --foreground --debug 2>scratch/error
    sleep 0.1
    sed -i -n '/parse/s/[^]]*]//p' scratch/error
    cmp scratch/error << EOF
: Debug: Unable to parse '$(pwd)/scratch/xkeyboard'
EOF
    RES=$?
fi

if [ $RES = 0 ]; then
    echo PASS No End Section
    sleep 0.1
    cat > scratch/xkeyboard <<- EOF
	Section "Screen"
	        Option "XkbLayout" "fr"
	EndSection
	EOF
    . ${srcdir}/ref-localed.sh --foreground --debug 2>scratch/error
    sleep 0.1
#    sed -i -n '/parse/s/[^]]*]//p' scratch/error
    cmp scratch/error << EOF
: Debug: Unable to parse '$(pwd)/scratch/xkeyboard'
EOF
    RES=$?
fi

if [ $RES = 0 ]; then rm scratch/{xkeyboard,error}; fi
. ${srcdir}/unref-localed.sh
. ${srcdir}/unref-dbus.sh
exit $RES
