.TH "BLOCALED" "8" "October 2019" "blocaled" "blocaled"
.SH "NAME"
blocaled \- locale settings D\-Bus service
.SH "SYNOPSIS"
\fBblocaled\fR [\fB\-\-debug\fR] [\fB\-\-foreground\fR] [\fB\-\-read\-only\fR]
.SH "DESCRIPTION"
.PP
The \fBblocaled\fR daemon implements the standard localed
(i.e. \fIorg.freedesktop.locale1\fR) D\-Bus interface as a stand-alone daemon.
Users and administrators should not need to launch the \fBblocaled\fR
executable manually. It will be launched automatically via D\-Bus activation
when needed.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Show help options.
.RE
.PP
\fB\-\-version\fR
.RS 4
Show version information.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Enable debugging messages. Not recommended unless in foreground mode.
.RE
.PP
\fB\-\-foreground\fR
.RS 4
Run in foreground mode (i.e. not daemonized). Messages will be logged to stderr
instead of the system log.
.RE
.PP
\fB\-\-read\-only\fR
.RS 4
Run daemon in read-only mode. It will read settings files, but will not
modify them.
.RE
.SH "AUTHORS"
.PP
The code for this daemon is adapted from the \fBopenrc-settingsd\fR(8) project
written by
.MT tetromino@gentoo.org
Alexandre Rostovtsev
.ME . The port to standalone has been done by
.MT pierre.labastie@neuf.fr
Pierre Labastie
.ME .
.SH "BUGS"
.PP
Bug reports should be submitted to
.UR https://github.com/pierre-labastie/blocaled/issues
.UE .
.SH "SEE ALSO"
.PP
\fBdbus\-daemon\fR(1), \fBpolkit\fR(8)
