.TH "OPENRC-SETTINGSD" "8" "September 2012" "OpenRC-settingsd" "openrc-settingsd"
.SH "NAME"
openrc\-settingsd \- system settings D\-Bus service for OpenRC
.SH "SYNOPSIS"
\fBopenrc\-settingsd\fR [\fB\-\-help\fR] [\fB\-\-debug\fR] [\fB\-\-read\-only\fR]
[\fB\-\-foreground\fR] [\fB\-\-update\-rc\-status\fR] [\fB\-\-ntp\-service\fR=\fISERVICE\fR]
.SH "DESCRIPTION"
.PP
The \fBopenrc\-settingsd\fR daemon implements the standard hostnamed (i.e.
\fIorg.freedesktop.hostname1\fR), localed (i.e. \fIorg.freedesktop.locale1\fR), and
timedated (\fIorg.freedesktop.timedate1\fR) D\-Bus interfaces for OpenRC systems.
Users and administrators should not need to launch the \fBopenrc\-settingsd\fR
executable manually. Depending on the installation, it will either be launched
automatically via D\-Bus activation when needed, or started by the administrator
as an OpenRC service using \fI/etc/init.d/openrc\-settingsd\fR.    
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Show help options.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Enable debugging messages. Not recommended unless in foreground mode.
.RE
.PP
\fB\-\-read\-only\fR
.RS 4
Run daemon in read-only mode. It will read settings files, but will not
modify them.
.RE
.PP
\fB\-\-foreground\fR
.RS 4
Run in foreground mode (i.e. not daemonized). Messages will be logged to stderr
instead of the system log.
.RE
.PP
\fB\-\-update\-rc\-status\fR
.RS 4
Automatically set the status of the \fIopenrc\-settingsd\fR service to \fIstarted\fR
when the daemon successfully starts, and to \fIstopped\fR when the daemon stops. If
\fBopenrc\-settingsd\fR is manually launched with this argument, the administrator
will be able to stop it via \fI/etc/init.d/openrc\-settingsd\fR\ \fIstop\fR.
.RE
.PP
\fB\-\-ntp\-service\fR=\fISERVICE\fR
.RS 4
Specify which OpenRC service to use as the NTP service. If this option is not used,
\fBopenrc\-settingsd\fR will attempt to autodetect an appropriate ntp implementation.
.RE
.SH "AUTHORS"
.PP
Written by
.MT tetromino@gentoo.org
Alexandre Rostovtsev
.ME .
.SH "BUGS"
.PP
Bug reports should be submitted to the
.UR https://bugs.gentoo.org/
Gentoo Bugzilla
.UE ; use \fIGNOME\fR as the component.
.SH "SEE ALSO"
.PP
\fBdbus\-daemon\fR(1), \fBpolkit\fR(8), \fBrc\fR(8)